name: Cloudflare DNS Records

on:
  workflow_dispatch:
    inputs:
      target_ip:
        description: 'Target IP address (leave empty to use secret)'
        required: false
        type: string
  schedule:
    # Run every 6 hours to keep DNS updated
    - cron: '0 */6 * * *'

env:
  # DNS records to manage for 7gram.xyz
  DNS_RECORDS: >-
    7gram.xyz
    *.7gram.xyz
    auth.7gram.xyz
    nc.7gram.xyz
    photo.7gram.xyz
    home.7gram.xyz
    obs-demo.7gram.xyz
    obs-live.7gram.xyz
    obf-demo.7gram.xyz
    obf-live.7gram.xyz
    sync-freddy.7gram.xyz
    sync-sullivan.7gram.xyz
    sync-oryx.7gram.xyz
    sync-desktop.7gram.xyz
    grocy.7gram.xyz
    mealie.7gram.xyz
    wiki.7gram.xyz
    duplicati.7gram.xyz
    jellyfin.7gram.xyz
    emby.7gram.xyz
    plex.7gram.xyz
    sonarr.7gram.xyz
    radarr.7gram.xyz
    lidarr.7gram.xyz
    jackett.7gram.xyz
    qbittorrent.7gram.xyz
    yt.7gram.xyz
    filebot.7gram.xyz
    calibre.7gram.xyz

jobs:
  update-dns:
    runs-on: ubuntu-latest
    name: Cloudflare DNS
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set target IP
        id: ip
        run: |
          if [ -n "${{ inputs.target_ip }}" ]; then
            echo "TARGET_IP=${{ inputs.target_ip }}" >> $GITHUB_ENV
            echo "Using workflow input IP: ${{ inputs.target_ip }}"
          else
            echo "TARGET_IP=${{ secrets.DNS_TARGET_IP }}" >> $GITHUB_ENV
            echo "Using secret IP"
          fi

      - name: Validate IP address
        run: |
          if [[ ! "$TARGET_IP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            echo "Error: Invalid IP address format: $TARGET_IP"
            exit 1
          fi
          echo "✓ Valid IP address: $TARGET_IP"

      - name: Cloudflare DNS records
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          echo "Updating DNS records for 7gram.xyz..."
          
          # Function to get DNS record ID
          get_record_id() {
            local record_name=$1
            curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/dns_records?name=${record_name}" \
              -H "Authorization: Bearer ${CF_API_TOKEN}" \
              -H "Content-Type: application/json" | jq -r '.result[0].id // empty'
          }
          
          # Function to create or update DNS record
          update_dns_record() {
            local record_name=$1
            local record_type="A"
            local record_id=$(get_record_id "$record_name")
            
            if [ -z "$record_id" ]; then
              echo "Creating new record: $record_name -> $TARGET_IP"
              response=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/dns_records" \
                -H "Authorization: Bearer ${CF_API_TOKEN}" \
                -H "Content-Type: application/json" \
                --data "{\"type\":\"${record_type}\",\"name\":\"${record_name}\",\"content\":\"${TARGET_IP}\",\"ttl\":1,\"proxied\":false}")
            else
              echo "Updating existing record: $record_name -> $TARGET_IP"
              response=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/dns_records/${record_id}" \
                -H "Authorization: Bearer ${CF_API_TOKEN}" \
                -H "Content-Type: application/json" \
                --data "{\"type\":\"${record_type}\",\"name\":\"${record_name}\",\"content\":\"${TARGET_IP}\",\"ttl\":1,\"proxied\":false}")
            fi
            
            success=$(echo "$response" | jq -r '.success')
            if [ "$success" = "true" ]; then
              echo "✓ Successfully updated $record_name"
            else
              echo "✗ Failed to update $record_name"
              echo "$response" | jq -r '.errors[]'
              return 1
            fi
          }
          
          # Update each DNS record
          failed=0
          for record in $DNS_RECORDS; do
            if ! update_dns_record "$record"; then
              failed=$((failed + 1))
            fi
            sleep 1  # Rate limiting
          done
          
          if [ $failed -gt 0 ]; then
            echo "Failed to update $failed record(s)"
            exit 1
          fi
          
          echo "✓ All DNS records updated successfully!"

      - name: Verify DNS propagation
        run: |
          echo "Waiting for DNS propagation..."
          sleep 10
          
          # Test a few key records
          for record in "7gram.xyz" "auth.7gram.xyz" "octobot-spot.7gram.xyz"; do
            resolved_ip=$(dig +short "$record" @1.1.1.1 | tail -n1)
            if [ "$resolved_ip" = "$TARGET_IP" ]; then
              echo "✓ $record resolves to $TARGET_IP"
            else
              echo "⚠ $record resolves to $resolved_ip (expected $TARGET_IP)"
            fi
          done

      - name: Create summary
        if: always()
        run: |
          echo "## DNS Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Target IP:** $TARGET_IP" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Updated Records" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          for record in $DNS_RECORDS; do
            echo "- $record" >> $GITHUB_STEP_SUMMARY
          done
